# AUTOGENERATED! DO NOT EDIT! File to edit: 00_config.ipynb (unless otherwise specified).

__all__ = ['FORMAT', 'logger', 'env', 'CACHE_DIR', 'DOTPATH']

# Cell
from environs import Env
import logging

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT)
logger = logging.getLogger('ocandata')
logger.setLevel(logging.DEBUG)

env = Env()
env.read_env()

CACHE_DIR = env('cache_dir', '.')
DOTPATH = env('DOTPATH', 'canadadata')